services:
  - type: web
    name: eexi-calculator-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --config app/gunicorn_config.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.12.9
